#!/bin/bash
setenforce 0
#下载装包
lftp 172.25.254.250:/notes/project/UP200/UP200_cacti-master> mirror pkg/
yum -y install httpd php php-mysql mariadb-server mariadb
yum localinstall cacti-0.8.8b-7.el7.noarch.rpm php-snmp-5.4.16-23.el7_0.3.x86_64.rpm 
#以管理员命令mysqladmin配置mysql数据库
service mariadb start
mysqladmin -uroot password "uplooking"
mysqladmin -uroot -puplooking create cacti
echo "grant all on cacti.* to rcactidb@'localhost' identified by '123456';" | mysql -uroot -puplooking
mysqladmin -uroot -puplooking flush-privileges

#修改配置文件
cat> /etc/cacti/db.php << EOT
<?php
/*
 +-------------------------------------------------------------------------+
 | Copyright (C) 2004-2013 The Cacti Group                                 |
 |                                                                         |
 | This program is free software; you can redistribute it and/or           |
 | modify it under the terms of the GNU General Public License             |
 | as published by the Free Software Foundation; either version 2          |
 | of the License, or (at your option) any later version.                  |
 |                                                                         |
 | This program is distributed in the hope that it will be useful,         |
 | but WITHOUT ANY WARRANTY; without even the implied warranty of          |
 | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           |
 | GNU General Public License for more details.                            |
 +-------------------------------------------------------------------------+
 | Cacti: The Complete RRDTool-based Graphing Solution                     |
 +-------------------------------------------------------------------------+
 | This code is designed, written, and maintained by the Cacti Group. See  |
 | about.php and/or the AUTHORS file for specific developer information.   |
 +-------------------------------------------------------------------------+
 | http://www.cacti.net/                                                   |
 +-------------------------------------------------------------------------+
*/

/* make sure these values refect your actual database/host/user/password */
$database_type = "mysql";
$database_default = "cacti";
$database_hostname = "localhost";
$database_username = "cactidb";
$database_password = "123456";
$database_port = "3306";
$database_ssl = false;

/*
   Edit this to point to the default URL of your Cacti install
   ex: if your cacti install as at http://serverip/cacti/ this
   would be set to /cacti/
*/
//$url_path = "/cacti/";

/* Default session name - Session name must contain alpha characters */
//$cacti_session_name = "Cacti";

?>
EOT

#导入
mysql -ucactidb -p123456 cacti < /usr/share/doc/cacti-0.8.8b/cacti.sql 

#配置cacti的相关参数

cat >/etc/httpd/conf.d/cacti.conf << EOT
#
# Cacti: An rrd based graphing tool
#

# For security reasons, the Cacti web interface is accessible only to
# localhost in the default configuration. If you want to allow other clients
# to access your Cacti installation, change the httpd ACLs below.
# For example:
# On httpd 2.4, change "Require host localhost" to "Require all granted".
# On httpd 2.2, change "Allow from localhost" to "Allow from all".

Alias /cacti    /usr/share/cacti

<Directory /usr/share/cacti/>
	<IfModule mod_authz_core.c>
		# httpd 2.4
		Require all granted
	</IfModule>
	<IfModule !mod_authz_core.c>
		# httpd 2.2
		Order deny,allow
		Deny from all
		Allow from localhost
	</IfModule>
</Directory>

<Directory /usr/share/cacti/install>
	# mod_security overrides.
	# Uncomment these if you use mod_security.
	# allow POST of application/x-www-form-urlencoded during install
	#SecRuleRemoveById 960010
	# permit the specification of the rrdtool paths during install
	#SecRuleRemoveById 900011
</Directory>


# These sections marked "Require all denied" (or "Deny from all")
# should not be modified.
# These are in place in order to harden Cacti.
<Directory /usr/share/cacti/log>
	<IfModule mod_authz_core.c>
		Require all denied
	</IfModule>
	<IfModule !mod_authz_core.c>
		Order deny,allow
		Deny from all
	</IfModule>
</Directory>
<Directory /usr/share/cacti/rra>
	<IfModule mod_authz_core.c>
		Require all denied
	</IfModule>
	<IfModule !mod_authz_core.c>
		Order deny,allow
		Deny from all
	</IfModule>
</Directory>
EOT

#配置php时区
timedatectl set-timezone Asia/Shanghai
sed -i 's/^data.timezone.*/data.timezone = Asia\/Shanghai/' /etc/php.ini 

#变更计划任务 --> 让其五分钟出一一次图####

echo '*/5 * * * *     cacti   /usr/bin/php /usr/share/cacti/poller.php > /dev/null 2>&1' >>  /etc/cron.d/cacti 


#启动服务####
service httpd restart
service snmpd restart
#netstat -anlp |grep :161


#访问测试:通过 图形化浏览器来访问:####


